name: easymotorbike
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  country_code_picker: ^3.0.0
  url_launcher: ^6.3.1
  carousel_slider: ^5.0.0
  firebase_core: ^3.6.0
  font_awesome_flutter: ^10.8.0
  camera: ^0.11.0+2
  google_maps_flutter: ^2.9.0
  torch_light: ^1.1.0
  permission_handler: ^11.3.1
  location: ^7.0.1
  easy_localization: ^3.0.7
  shared_preferences: ^2.3.3
  http: ^1.2.2
  geolocator: ^13.0.2
  jwt_decoder: ^2.0.1
  package_info_plus: ^8.1.1
  geocoding: ^3.0.0
  latlong2: ^0.9.1
  image_picker: ^1.1.2
  connectivity_plus: ^6.1.2
  firebase_messaging: ^15.2.0
  flutter_local_notifications: ^18.0.1
  app_settings: ^5.1.1
  firebase_analytics: ^11.4.0
  intl: any
  lottie: ^3.2.0
  provider: ^6.1.2
  qr_code_scanner: ^1.0.1
  flutter_launcher_icons: ^0.14.3
  webview_flutter: ^4.12.0
  crypto: ^3.0.6
  flutter_inappwebview: ^6.1.5
  convex_bottom_bar: ^3.2.0
  google_sign_in: ^6.3.0
  firebase_auth: ^5.5.4
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
    
flutter:
  uses-material-design: true

  
  assets:
    - assets/
    - assets/lang/

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"
  remove_alpha_ios: true
