// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbAE2JM9lFgzpGyWRrbhJU-aRMuli6P4w',
    appId: '1:396255044410:web:121ea43f5a8b40c645e603',
    messagingSenderId: '396255044410',
    projectId: 'easyride-kl',
    authDomain: 'easyride-kl.firebaseapp.com',
    storageBucket: 'easyride-kl.firebasestorage.app',
    measurementId: 'G-LQ287L08VL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzzok7Fv5JMRMJGFl0n-VfDMpiML5T-V4',
    appId: '1:396255044410:android:dd7aa201cd38bed745e603',
    messagingSenderId: '396255044410',
    projectId: 'easyride-kl',
    storageBucket: 'easyride-kl.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAT4Cpv5lmj8fq4wagnOQxFW3adDl64dbs',
    appId: '1:396255044410:ios:855ae0ff8273051b45e603',
    messagingSenderId: '396255044410',
    projectId: 'easyride-kl',
    storageBucket: 'easyride-kl.firebasestorage.app',
    iosBundleId: 'com.gaurav.easymotorbike.easymotorbike',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAT4Cpv5lmj8fq4wagnOQxFW3adDl64dbs',
    appId: '1:396255044410:ios:855ae0ff8273051b45e603',
    messagingSenderId: '396255044410',
    projectId: 'easyride-kl',
    storageBucket: 'easyride-kl.firebasestorage.app',
    iosBundleId: 'com.gaurav.easymotorbike.easymotorbike',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDbAE2JM9lFgzpGyWRrbhJU-aRMuli6P4w',
    appId: '1:396255044410:web:2611d239076ea9df45e603',
    messagingSenderId: '396255044410',
    projectId: 'easyride-kl',
    authDomain: 'easyride-kl.firebaseapp.com',
    storageBucket: 'easyride-kl.firebasestorage.app',
    measurementId: 'G-WXQ9P8GY7E',
  );
}
