// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-GjLfiOLzYSgHydH1Snt7V-XnEiIIFTs',
    appId: '1:882626800374:web:a9b3aed2cfff53f74e5ad7',
    messagingSenderId: '882626800374',
    projectId: 'easyride-e04a2',
    authDomain: 'easyride-e04a2.firebaseapp.com',
    storageBucket: 'easyride-e04a2.firebasestorage.app',
    measurementId: 'G-5RVYSFRC89',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDyjRtNqAix66_mkubClvFT64f26jvYOhk',
    appId: '1:882626800374:android:0f99ba5d9f1c02d54e5ad7',
    messagingSenderId: '882626800374',
    projectId: 'easyride-e04a2',
    storageBucket: 'easyride-e04a2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVuqUe45sZi2y7RR5uXHbda2qk4Ea2-SU',
    appId: '1:882626800374:ios:7b76364fa910f9bc4e5ad7',
    messagingSenderId: '882626800374',
    projectId: 'easyride-e04a2',
    storageBucket: 'easyride-e04a2.firebasestorage.app',
    iosBundleId: 'com.example.easyride',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDVuqUe45sZi2y7RR5uXHbda2qk4Ea2-SU',
    appId: '1:882626800374:ios:7b76364fa910f9bc4e5ad7',
    messagingSenderId: '882626800374',
    projectId: 'easyride-e04a2',
    storageBucket: 'easyride-e04a2.firebasestorage.app',
    iosBundleId: 'com.example.easyride',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA-GjLfiOLzYSgHydH1Snt7V-XnEiIIFTs',
    appId: '1:882626800374:web:d1679356cc6ea9144e5ad7',
    messagingSenderId: '882626800374',
    projectId: 'easyride-e04a2',
    authDomain: 'easyride-e04a2.firebaseapp.com',
    storageBucket: 'easyride-e04a2.firebasestorage.app',
    measurementId: 'G-6NSBH24XB2',
  );
}
